### ISSUE TITLE
Please help!

### ISSUE THREAD

**Issue by Samirahajiragab** [Samirahajiragab/volunteer-form#1]
There is something wrong with my coding, I couldn't seem to fix it. Would you please check it and the "radio" doesn't function even when I change the names. 

Thank you for your time.
@muxlowc

**Comment by muxlowc** [comment]
@Samirahajiragab you're on the right track!

1) your "input **id**" and "label **for**" need to be the same and should be somewhat descriptive for the question (like in example below: "licence-yes" ) -this is just telling your code that this label goes specifically with this input.
2) Your "input **name**" should be the same on each input in the group of anwsers (ie. both Yes/No answers have the name="licence" below) - This is telling these two answers that they are part of the same question (so you should only be able to select one...Radio buttons=Single answer only)

Here is a snippet from the solution:
`
<fieldset class="pad-t-1-2 push-2">

        <legend class="gutter-1-2 giga">Do you have a valid driver’s license?</legend>

        <div class="inline-block pad-t-1-8 pad-b-1-8 gutter-1-2 push-r-1-2">
          <input type="radio" id="license-yes" name="license" required>
          <label for="license-yes">Yes</label>
        </div>

        <div class="inline-block pad-t-1-8 pad-b-1-8 gutter-1-2 ">
          <input type="radio" id="license-no" name="license" required>
          <label for="license-no">No</label>
        </div>
      </fieldset>`

Sorry, I hope that makes sense! If you watch Thomas' videos, it might be easier to see him actually code it.

**Comment by Samirahajiragab** [comment]
<img width="508" alt="image" src="https://user-images.githubusercontent.com/55094325/77105616-4fcd1b00-69f4-11ea-9d33-c5fa1b276cb2.png">

Thank you so much, it does make sense!
1.What about the date of birth since I can't use placeholder what else should I use?

2.  I think my coding is wrong because I can't match the screenshots. Even though it looks fine Markbot seem to not except it :(

**Comment by muxlowc** [comment]
@Samirahajiragab so you don't need to add a placeholder for type=date .. it will automatically do that for you :)

Your Header should only have your H2 and Paragraph (your header shouldn't contain all of your content, it should only contain the most important info like logo/h1 etc), so close your Header right after your H2/p

Add a wrapper class on your form (this is why your content is spanning across the whole screen, because it thinks it needs to be 100% width b/c it's not being told otherwise.

Did you push your most recent code? When I forked your code Markbot was still giving out a few errors that you should be able to fix pretty easily

**Comment by Samirahajiragab** [comment]
I have fixed most of the content but I still there stuff that I didn't know how to fix?
@muxlowc

**Comment by Samirahajiragab** [comment]
I have fixed most of the content but I still there stuff that I didn't know how to fix?
@mackenzierose

**Comment by Samirahajiragab** [comment]
I have fixed most of the content but I still there stuff that I didn't know how to fix?
@mackenzierose
@muxlowc
