### ISSUE TITLE
Still can't submit 

### ISSUE THREAD

**Issue by Samirahajiragab** [Samirahajiragab/volunteer-form#2]
I have fixed most of the content but I still there stuff that I didn't know how to fix?
@muxlowc

**Comment by muxlowc** [comment]
@Samirahajiragab 

1) you'll need to tell your header and footer to be green, rather than the whole body, and then you'll have to add a wrapper to make your header be the same width as the rest of your content (which you'll have to add a div, because if you add the wrapper class to your header, the green won't expand 100%):
```
<header class="pad-t pad-b push-2 green-bg">
    <div class="wrapper">
      <h1 class=.....
```
I added the "green-bg" class to the header and footer - and added the background colour to this class in css.

2) You are also missing "Unit" classes on your checkboxes it looks like:
```
        <div class="grid">
          <div class="unit xs-1 s-1 m-1-2 l-1-2 gutter-1-2">
            <div class="pad-t-1-8 pad-b-1-8">
              <input type="checkbox" id="digging-holes">
              <label for="digging-holes">Digging holes</label>
            </div>
```

**Comment by Samirahajiragab** [comment]
sorry, there is more to fix :(, I got is close to 30%
Why is my page shorter the one in the screenshot
@muxlowc
